FROM golang:1.24.4 AS builder

WORKDIR /publisher

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd /publisher/cmd
COPY ./internal /publisher/internal

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/publisher/

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /publisher/main .

CMD ["./main"]