FROM golang:1.24.4 AS builder

WORKDIR /event

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd /event/cmd
COPY ./internal /event/internal

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/event/

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /event/main .

CMD ["./main"]