FROM golang:1.24.4 AS builder

WORKDIR /subscriber

COPY go.mod go.sum ./
RUN go mod download

COPY ./cmd /subscriber/cmd
COPY ./internal /subscriber/internal

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/subscriber/

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /subscriber/main .

CMD ["./main"]